stages:
  - test
  - deploy

test-job:
  image: debian
  stage: test
  script:
    - apt update 
    - apt install curl -y 
    - curl "https://caddyserver.com/api/download?os=linux&arch=amd64&idempotency=92414842093288" -o caddy -L
    - chmod +x ./caddy
    - ./caddy validate Caddyfile

deploy-job:
  image: debian
  stage: deploy
  script:
    - mv Caddyfile ilearned.conf
    - apt update 
    - apt install openssh-client rsync -y 
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" ilearned.conf deploy@vm01.eban.eu.org:/etc/caddy/
    - ssh -i ~/.ssh/id_ed25519 deploy@vm01.eban.eu.org sudo systemctl restart caddy